INSTALL_DIR ?= /usr/local/bin
BINARY_NAME = forge
BUILD_CONFIGURATION = release
VERSION := $(shell git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//' || echo "dev")

.PHONY: build install uninstall generate-version

# Updates Version.swift only if the version actually changed (avoids triggering unnecessary rebuilds)
generate-version:
	@CURRENT_VERSION=$$(sed -n 's/.*forgeVersion = "\(.*\)".*/\1/p' Sources/forge/Version.swift 2>/dev/null); \
	if [ "$$CURRENT_VERSION" != "$(VERSION)" ]; then \
		echo "// Auto-generated by Makefile — do not edit manually." > Sources/forge/Version.swift; \
		echo "let forgeVersion = \"$(VERSION)\"" >> Sources/forge/Version.swift; \
		echo "Generated Sources/forge/Version.swift ($(VERSION))"; \
	fi

build: generate-version
	swift build -c $(BUILD_CONFIGURATION)

install: build
	install -d "$(INSTALL_DIR)"
	install -m 755 ".build/$(BUILD_CONFIGURATION)/$(BINARY_NAME)" "$(INSTALL_DIR)/$(BINARY_NAME)"
	@echo "Installed $(BINARY_NAME) $(VERSION) to $(INSTALL_DIR)/$(BINARY_NAME)"

uninstall:
	rm -f "$(INSTALL_DIR)/$(BINARY_NAME)"
	@echo "Removed $(INSTALL_DIR)/$(BINARY_NAME)"
